# Generated by Django 5.1.7 on 2025-04-29 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(default='usuario', max_length=200)),
                ('email', models.EmailField(default='usuario@gmail.com', max_length=254)),
                ('senha', models.CharField(default='senha', max_length=20)),
                ('produtos_comprados', models.ManyToManyField(blank=True, related_name='produtos_comprados', to='empresas.produto')),
            ],
        ),
    ]
