# Generated by Django 5.1.6 on 2025-04-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='produtos_comprados',
            field=models.ManyToManyField(blank=True, related_name='produtos_comprados', to='empresas.produto'),
        ),
    ]
