# Generated by Django 5.1.7 on 2025-04-29 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dono_empresa', models.CharField(default='dono da empresa', max_length=150)),
                ('nome_empresa', models.CharField(max_length=80, unique=True)),
                ('faturamento', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(default='produto', max_length=100)),
                ('quantidade_estoque', models.IntegerField(default=0)),
                ('preco', models.FloatField(default=0)),
                ('imagem_src', models.ImageField(default='produtos/cart.png', upload_to='produtos/')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='empresas.empresa')),
            ],
        ),
    ]
