# Generated by Django 5.1.6 on 2025-04-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem_src',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
