# Generated by Django 5.1.6 on 2025-03-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='nome_produto',
            field=models.CharField(default='produto', max_length=100),
        ),
    ]
