# Generated by Django 5.1.6 on 2025-04-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_produto_imagem_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem_src',
            field=models.CharField(default="static 'img/cart.png'", max_length=300),
        ),
    ]
