# Generated by Django 5.1.6 on 2025-03-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_produto_nome_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nome_empresa',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
