# Generated by Django 5.1.7 on 2025-04-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_produto_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='imagem_perfil',
            field=models.ImageField(default='empresas_perfil/empresa.jpeg', upload_to='empresas_perfil/'),
        ),
    ]
