# Generated by Django 5.1.7 on 2025-04-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_empresa_imagem_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem_src',
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_url',
            field=models.URLField(default='https://via.placeholder.com/150'),
        ),
    ]
