# Generated by Django 5.1.6 on 2025-03-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0004_delete_empresa_delete_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(default='produto', max_length=100)),
                ('quantidade_estoque', models.IntegerField(default=0)),
                ('preco', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(default='empresa', max_length=80)),
                ('faturamento', models.FloatField(default=0)),
                ('produtos', models.ManyToManyField(to='empresas.produto')),
            ],
        ),
    ]
