# Generated by Django 5.1.7 on 2025-05-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_remove_produto_imagem_src_produto_imagem_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem_url',
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_src',
            field=models.ImageField(default='produtos/cart.png', upload_to='produtos/'),
        ),
    ]
