# Generated by Django 5.1.6 on 2025-04-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_alter_produto_imagem_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem_src',
            field=models.ImageField(default='templates/static/img/cart.png', upload_to='templates/static/img/'),
        ),
    ]
