# Generated by Django 5.1.7 on 2025-03-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_alter_empresa_nome_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='dono_empresa',
            field=models.CharField(default='dono da empresa', max_length=150),
        ),
    ]
