# Generated by Django 5.1.7 on 2025-03-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_empresa_dono_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome_produto',
            field=models.CharField(default='produto', max_length=100, null=True),
        ),
    ]
