# Generated by Django 5.1.7 on 2025-03-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_alter_produto_nome_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade_estoque',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
