# Generated by Django 5.1.7 on 2025-03-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0009_alter_produto_preco_alter_produto_quantidade_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome_produto',
            field=models.CharField(default='produto', max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade_estoque',
            field=models.IntegerField(default=0),
        ),
    ]
