# Generated by Django 5.1.6 on 2025-03-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_alter_produto_nome_produto_alter_produto_preco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(default='usuario', max_length=200)),
                ('email', models.EmailField(default='usuario@gmail.com', max_length=254)),
                ('senha', models.CharField(default='senha', max_length=20)),
            ],
        ),
    ]
