# Generated by Django 5.1.6 on 2025-03-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0011_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='produtos_comprados',
            field=models.ManyToManyField(to='empresas.produto'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='saldo',
            field=models.FloatField(default=0),
        ),
    ]
